        !COMPILER-GENERATED INTERFACE MODULE: Fri May 10 09:47:41 2013
        MODULE COMBINENODES__genmod
          INTERFACE 
            SUBROUTINE COMBINENODES(DZMIN,A1SNOW,THSNOW,TLSNOW,SSISNOW)
              REAL(KIND=8) :: DZMIN
              REAL(KIND=8) :: A1SNOW
              REAL(KIND=8) :: THSNOW
              REAL(KIND=8) :: TLSNOW
              REAL(KIND=8) :: SSISNOW
            END SUBROUTINE COMBINENODES
          END INTERFACE 
        END MODULE COMBINENODES__genmod
