        !COMPILER-GENERATED INTERFACE MODULE: Fri May 10 09:47:47 2013
        MODULE OUTFILTRATE__genmod
          INTERFACE 
            SUBROUTINE OUTFILTRATE(ITITLE,IBOUNDS,IHOUR,DTSUM,NZONE,JDAY&
     &)
              INTEGER(KIND=4) :: ITITLE
              INTEGER(KIND=4) :: IBOUNDS(15,2)
              INTEGER(KIND=4) :: IHOUR
              REAL(KIND=8) :: DTSUM
              INTEGER(KIND=4) :: NZONE
              INTEGER(KIND=4) :: JDAY
            END SUBROUTINE OUTFILTRATE
          END INTERFACE 
        END MODULE OUTFILTRATE__genmod
