        !COMPILER-GENERATED INTERFACE MODULE: Fri May 10 09:47:41 2013
        MODULE POROSTY__genmod
          INTERFACE 
            SUBROUTINE POROSTY(DICEVOL,DMVOL,LTYPE,POROSITY,            &
     &SOLIDPOROSITY)
              REAL(KIND=8) :: DICEVOL
              REAL(KIND=8) :: DMVOL
              INTEGER(KIND=4) :: LTYPE
              REAL(KIND=8) :: POROSITY
              REAL(KIND=8) :: SOLIDPOROSITY
            END SUBROUTINE POROSTY
          END INTERFACE 
        END MODULE POROSTY__genmod
