        !COMPILER-GENERATED INTERFACE MODULE: Fri May 10 09:47:40 2013
        MODULE SHALLOW__genmod
          INTERFACE 
            SUBROUTINE SHALLOW(ALBINFV,ALBINFN,ALBSOIL,FVIS)
              REAL(KIND=8) :: ALBINFV
              REAL(KIND=8) :: ALBINFN
              REAL(KIND=8) :: ALBSOIL
              REAL(KIND=8) :: FVIS
            END SUBROUTINE SHALLOW
          END INTERFACE 
        END MODULE SHALLOW__genmod
