        !COMPILER-GENERATED INTERFACE MODULE: Fri May 10 09:47:28 2013
        MODULE SUBTIME__genmod
          INTERFACE 
            SUBROUTINE SUBTIME(REPEAT)
              LOGICAL(KIND=4) :: REPEAT
            END SUBROUTINE SUBTIME
          END INTERFACE 
        END MODULE SUBTIME__genmod
