        !COMPILER-GENERATED INTERFACE MODULE: Fri May 10 09:47:50 2013
        MODULE THERMAL__genmod
          INTERFACE 
            SUBROUTINE THERMAL(DTMIN,DZMIN,RECROSS,*,ERRTALLOWD)
              REAL(KIND=8) :: DTMIN
              REAL(KIND=8) :: DZMIN
              LOGICAL(KIND=4) :: RECROSS
              REAL(KIND=8) :: ERRTALLOWD
            END SUBROUTINE THERMAL
          END INTERFACE 
        END MODULE THERMAL__genmod
