        !COMPILER-GENERATED INTERFACE MODULE: Fri May 10 09:47:46 2013
        MODULE THPARAM__genmod
          INTERFACE 
            SUBROUTINE THPARAM
            END SUBROUTINE THPARAM
          END INTERFACE 
        END MODULE THPARAM__genmod
