# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 01.py
# Created on: 2015-05-24 10:55:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

#循环开始
for n in xrange(2014,2015):
	for m in xrange(2,13):
		m="%02d" % m		#转换为两位日期
# Local variables:	
		
		data_class="TEM_"							#待处理的气象数据类型
		
	
##########################-----公用目录---------##############################################		
		input_dir="E:\\Climate\\climate\\50km\\Temp_14-15_50km\\SURF_CLI_CHN_TEM_MON_GRID_0.5-MEAN-"		#气象数据所在的目录
		output_dir="E:\\Climate\\climate\\50km\\Temp_14-15_50km\\"			#转换生成的栅格所在的目录
################################################################################		
		
#######################---转换后的每个流域结果的输出目录------#################################
		
		input_name=str(n)+m+".txt"
		output_name=data_class+str(n)+m+".tif"
######################-----待预处理的气象数据文件------##############################################		
		input_file = input_dir+input_name							#输入气象数据input_file1 = input_dir+output_name
		output_file = output_dir+output_name				#处理后的气象数据
		basin_clip="E:\\HUC\\basins\\basin_union_buffer.shp"
################################################################################
		
		
		print input_file,output_file


		# Process: ASCII to Raster
		arcpy.ASCIIToRaster_conversion(input_file, output_file, "FLOAT")

		# Process: Define Projection
		arcpy.DefineProjection_management(output_file, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

