# ---------------------------------------------------------------------------
# 功能：1、基于裁剪数据边界进行LAI数据的裁剪
#       2、提取出LAI栅格中”<100"的有效值
#		3、合并八天数据到月
# Created on: 星期日 十二月 18 2011 02:37:43 下午
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

#循环开始
for n in xrange(2000,2001):
	input_mu="K:\\Data\\MODIS\\MOD16A2\\MODET\\MODET\\MODET"
	output_mu="K:\\Data\\MODIS\\MOD16A2\\MODET\\annual\\MODET"
	
	input_01=input_mu+str(n)+"01.tif"
	input_02=input_mu+str(n)+"02.tif"
	input_03=input_mu+str(n)+"03.tif"
	input_04=input_mu+str(n)+"04.tif"
	input_05=input_mu+str(n)+"05.tif"
	input_06=input_mu+str(n)+"06.tif"
	input_07=input_mu+str(n)+"07.tif"
	input_08=input_mu+str(n)+"08.tif"
	input_09=input_mu+str(n)+"09.tif"
	input_10=input_mu+str(n)+"10.tif"
	input_11=input_mu+str(n)+"11.tif"
	input_12=input_mu+str(n)+"12.tif"
	
	
	output=output_mu+str(n)+".tif"
# Process: 像元统计数据
	arcpy.gp.CellStatistics_sa([input_01,input_02,input_03,input_04,input_05,input_06,input_07,input_08,input_09,input_10,input_11,input_12],output,"SUM","DATA")
	
	print "完成"+str(n)+"月到年的合并！"
