# ---------------------------------------------------------------------------
# 功能：1、提取出LAI栅格中”<100"的有效值
#       2、分植被类型进行LAI均值计算
# Created on: 星期日 十二月 18 2011 02:37:43 下午
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

#循环开始
for n in xrange(2011,2012):
#	for m in xrange(1,13):
#		m=range(1,13)
#		m="%02d" % m
	i=0
	for d in xrange(1,365,8):
		d="%03d" % d
		data_class="LAI"
##########################-----操作目录---------##############################################
		input_mulu="J:\\modis\\"		#输入TIF文件目录		
		out_mulu="G:\\wassic\\"	#输出有效值文件目录
		out_mulu_lai="D:\\\WASSI\\\ChangJiang\\"	#输出LAI计算结果目录
		input_mulu_basin="D:\\WASSI\\ChangJiang\\VEG_CJ\\"
		basins_dir="E:\\HUC\\VEG\\"
		
##########################-----输入文件---------##############################################
		input_tif1 = input_mulu+"MOD15A2.A"+str(n)+d+".Lai_1km.tif" 
		input_tif = input_mulu+"MOD15A2.A"+str(n)+d+"clip.tif" 		
		output_extra = out_mulu+"lai"+str(n)+d+".tif"	#提取后输出的tif文件
		name4=data_class+str(n)+d+".dbf"
		basin_clip="D:\\lai_ln1267\\basin_buffer_pro.shp"
##########################-----输入basin文件---------##############################################			
		basin_num_1="15"
		basin_num_2="20"
		basin_num_3="25"
		basin_num_4="30"
		basin_num_5="35"
		basin_num_6="45"
		basin_num_7="60"
		basin_num_8="80"
		basin_num_9="120"
		basin_num_10="200"
		basin_num_11="300"
		basin_num_12="458"
		basin_num_13="650"
		basin_num_14="1500"
		basin_num_15="4000"
		basin_num_16="20000"
		basin_num_17="20000"
		basin_num_18="2000"
			
		basin_1=basins_dir+"VEG_"+basin_num_1+".shp"	# 待统计流域边界
		basin_2=basins_dir+"VEG_"+basin_num_2+".shp"	# 待统计流域边界
		basin_3=basins_dir+"VEG_"+basin_num_3+".shp"	# 待统计流域边界
		basin_4=basins_dir+"VEG_"+basin_num_4+".shp"	# 待统计流域边界
		basin_5=basins_dir+"VEG_"+basin_num_5+".shp"	# 待统计流域边界
		basin_6=basins_dir+"VEG_"+basin_num_6+".shp"	# 待统计流域边界
		basin_7=basins_dir+"VEG_"+basin_num_7+".shp"	# 待统计流域边界
		basin_8=basins_dir+"VEG_"+basin_num_8+".shp"	# 待统计流域边界
		basin_9=basins_dir+"VEG_"+basin_num_9+".shp"	# 待统计流域边界
		basin_10=basins_dir+"VEG_"+basin_num_10+".shp"	# 待统计流域边界
		basin_11=basins_dir+"VEG_"+basin_num_11+".shp"	# 待统计流域边界
		basin_12=basins_dir+"VEG_"+basin_num_12+".shp"	# 待统计流域边界
		basin_13=basins_dir+"VEG_"+basin_num_13+".shp"	# 待统计流域边界
		basin_14=basins_dir+"VEG_"+basin_num_14+".shp"	# 待统计流域边界
		basin_15=basins_dir+"VEG_"+basin_num_15+".shp"	# 待统计流域边界
		basin_16=basins_dir+"VEG_"+basin_num_16+".shp"	# 待统计流域边界
		basin_17=basins_dir+"VEG_"+basin_num_17+".shp"	# 待统计流域边界
		basin_18=basins_dir+"VEG_"+basin_num_18+".shp"	# 待统计流域边界
######################-----分植被类型处理后的结果文件------##############################################
		output_data_dir_basin_1="E:\\HUC\\basin_"+basin_num_1+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_2="E:\\HUC\\basin_"+basin_num_2+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_3="E:\\HUC\\basin_"+basin_num_3+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_4="E:\\HUC\\basin_"+basin_num_4+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_5="E:\\HUC\\basin_"+basin_num_5+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_6="E:\\HUC\\basin_"+basin_num_6+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_7="E:\\HUC\\basin_"+basin_num_7+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_8="E:\\HUC\\basin_"+basin_num_8+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_9="E:\\HUC\\basin_"+basin_num_9+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_10="E:\\HUC\\basin_"+basin_num_10+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_11="E:\\HUC\\basin_"+basin_num_11+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_12="E:\\HUC\\basin_"+basin_num_12+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_13="E:\\HUC\\basin_"+basin_num_13+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_14="E:\\HUC\\basin_"+basin_num_14+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_15="E:\\HUC\\basin_"+basin_num_15+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_16="E:\\HUC\\basin_"+basin_num_16+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_17="E:\\HUC\\basin_"+basin_num_17+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_18="E:\\HUC\\basin_"+basin_num_18+"\\"+data_class+"\\"	#统计结果输出的目录





		output_data_basin_1=output_data_dir_basin_1+name4	#按表格统计结果输出的文件
		output_data_basin_2=output_data_dir_basin_2+name4	#按表格统计结果输出的文件
		output_data_basin_3=output_data_dir_basin_3+name4	#按表格统计结果输出的文件
		output_data_basin_4=output_data_dir_basin_4+name4	#按表格统计结果输出的文件
		output_data_basin_5=output_data_dir_basin_5+name4	#按表格统计结果输出的文件
		output_data_basin_6=output_data_dir_basin_6+name4	#按表格统计结果输出的文件
		output_data_basin_7=output_data_dir_basin_7+name4	#按表格统计结果输出的文件
		output_data_basin_8=output_data_dir_basin_8+name4	#按表格统计结果输出的文件
		output_data_basin_9=output_data_dir_basin_9+name4	#按表格统计结果输出的文件
		output_data_basin_10=output_data_dir_basin_10+name4	#按表格统计结果输出的文件
		output_data_basin_11=output_data_dir_basin_11+name4	#按表格统计结果输出的文件
		output_data_basin_12=output_data_dir_basin_12+name4	#按表格统计结果输出的文件
		output_data_basin_13=output_data_dir_basin_13+name4	#按表格统计结果输出的文件
		output_data_basin_14=output_data_dir_basin_14+name4	#按表格统计结果输出的文件
		output_data_basin_15=output_data_dir_basin_15+name4	#按表格统计结果输出的文件
		output_data_basin_16=output_data_dir_basin_16+name4	#按表格统计结果输出的文件
		output_data_basin_17=output_data_dir_basin_17+name4	#按表格统计结果输出的文件
		output_data_basin_18=output_data_dir_basin_18+name4	#按表格统计结果输出的文件
			
			
		print output_extra,output_data_basin_1
# Process: 计算统计数据
		arcpy.CalculateStatistics_management(input_tif1, "1", "1", "")
		print "成功统计栅格信息！"
			
# Process: 重新定义投影到Albers定义投影
		arcpy.DefineProjection_management(input_tif1, "PROJCS['Albers',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Albers'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',105.0],PARAMETER['Standard_Parallel_1',25.0],PARAMETER['Standard_Parallel_2',47.0],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]")
		print "定义投影为albers！"		
		
		
		
		# Process: 裁剪 (3)
		arcpy.Clip_management(input_tif1, "-569482.72309382 3210242.66760919 -96637.2454170428 3594357.64348364", input_tif, basin_clip, "", "ClippingGeometry")	

			
# Process: Extract by Attributes...
		arcpy.gp.ExtractByAttributes_sa(input_tif ,"\"value\" < 100 ", output_extra)
		print "成功提取出“<100“的值！"
# Process: 删除生成的栅格临时文件
		arcpy.gp.Delete_management(input_tif, "RasterDataset")
		print "成功删除TIF影像文件"
