# ---------------------------------------------------------------------------
# minus.py
# Created on: 2014-11-26 20:35:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


for n in xrange(2000,2010):
    m=n+1
    m="%02d" % m
    n="%02d" % n
    Dir="I:\\AU\\NDVI\\new\\tif\\"
    Dir2="F:\\NDVI\\min-mon\\"
    Var="NDVI-"
    # Local variables:
    RAIN_1 = Dir+Var+m+"03.tif"
    RAIN_2 = Dir+Var+n+"12.tif"
    Minus_tif = Dir2+"Min-3-12-"+n+".tif"

    # Process: Raster Calculator
    arcpy.gp.Minus_sa(RAIN_1, RAIN_2, Minus_tif)
    print n, m

