# ---------------------------------------------------------------------------
# 功能：1、提取出LIA栅格中”<100"的有效值
#       2、分植被类型进行LAI均值计算
# Created on: 星期日 十二月 18 2011 02:37:43 下午
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Check out any necessary licenses
gp.CheckOutExtension("spatial")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Spatial Analyst Tools.tbx")

for n in xrange(2001,2008):
#	for m in xrange(1,13):
#		m=range(1,13)
#		m="%02d" % m
		i=0
		for d in xrange(1,365,8):
			d="%03d" % d
			input_mulu="E:\\minjiang\\lai\\"	#输入文件目录		
			input_tif = input_mulu+"MOD15A2.A"+str(n)+d+".Lai_1km.tif"  
			# Local variables:
			out_mulu="d:\\output\\LAI_extract\\"	#输出文件目录
			output_extra = out_mulu+"MOD15A2.A"+str(n)+d+".Lai_1km.extra.tif"	#提取后输出的tif文件
#			stream_IGBP = "E:\\data\\岷江流域\\min_43_参数\\min_43_标识_IGBP.shp"
			stream_SAC = "E:\\data\\岷江流域\\min_43_参数\\min_43_veg.shp"

#			output_lai_igbp = out_mulu+"IGBP\\"+"IGBP_MOD15A2.A"+str(n)+d+".Lai_1km.dbf"
			output_lai_sac = out_mulu+"SAC\\"+"SAC_MOD15A2.A"+str(n)+d+".Lai_1km.dbf"
			print output_extra,stream_SAC,output_lai_sac


# Process: Extract by Attributes...
#			gp.ExtractByAttributes_sa(input_tif ,"\"value\" < 100 ", output_extra)

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
#			gp.ZonalStatisticsAsTable_sa(stream_IGBP, "ID", output_extra, output_lai_igbp, "DATA")
#			print "成功对岷江流域栅格进行统计"
		
# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
			gp.ZonalStatisticsAsTable_sa(stream_SAC, "ID", output_extra, output_lai_sac, "DATA")
			print "成功对岷江流域栅格进行统计"
