# ---------------------------------------------------------------------------
# Convert flt.py
# Created on: 2014-12-03 15:40:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

#循环开始
for n in xrange(2000,2014):
	for m in xrange(1,13):
		m="%02d" % m		#转换为两位日期
# Local variables:	
												#如果处理气象数据统计字段为"HUC_8"，统计LAI是则为”HUC_8"
		data_class="FWPT"							#待处理的数据类型”TM“，”PRE“，”LAI“
		data_class2="basin"					#判断是处理气象数据还是LAI数据；分别用“basin_"和“VEG_"
##########################-----流域划分个数---------##############################################			

# Local variables:
		input = "D:\\AU\\AWAP\\"+data_class+"\\mon\\flt\\mth_"+data_class+"_"+str(n)+m+".flt"
		output = "D:\\AU\\AWAP\\"+data_class+"\\mon\\tif\\"+data_class+"_"+str(n)+m+".tif"

		# Process: Float to Raster
		arcpy.FloatToRaster_conversion(input, output)

		# Process: Define Projection
		arcpy.DefineProjection_management(output, "GEOGCS['GCS_GDA_1994',DATUM['D_GDA_1994',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

		print m,n
