# ---------------------------------------------------------------------------
# mean.py
# Created on: 2014-11-17 12:51:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

path="D:\\AU\\NDVI\\5\\tif\\NDVI_05_band"
outpath="D:\\AU\\NDVI\\5\\ann\\NDVI_"

for m in xrange(0,13):
    n=m*12

    # Local variables:
    NDVI_1 = path+str(n+1)+".img"
    NDVI_2 = path+str(n+2)+".img"
    NDVI_3 = path+str(n+3)+".img"
    NDVI_4 = path+str(n+4)+".img"
    NDVI_5 = path+str(n+5)+".img"
    NDVI_6 = path+str(n+6)+".img"
    NDVI_7 = path+str(n+7)+".img"
    NDVI_8 = path+str(n+8)+".img"
    NDVI_9 = path+str(n+9)+".img"
    NDVI_10 = path+str(n+10)+".img"
    NDVI_11 = path+str(n+11)+".img"
    NDVI_12 = path+str(n+12)+".img"
    mean_tif = outpath+str(m+2000)+"_mean.tif"
    max_tif = outpath+str(m+2000)+"_max.tif"
    min_tif = outpath+str(m+2000)+"_min.tif"
    range_tif = outpath+str(m+2000)+"_range.tif"
    std_tif = outpath+str(m+2000)+"_STD.tif"
    sum_tif = outpath+str(m+2000)+"_SUM.tif"
    # Process: Cell Statistics
    arcpy.gp.CellStatistics_sa([NDVI_1,NDVI_2,NDVI_3,NDVI_4,NDVI_5,NDVI_6,NDVI_7,NDVI_8,NDVI_9,NDVI_10,NDVI_12], sum_tif, "SUM", "DATA")
    arcpy.gp.CellStatistics_sa([NDVI_1,NDVI_2,NDVI_3,NDVI_4,NDVI_5,NDVI_6,NDVI_7,NDVI_8,NDVI_9,NDVI_10,NDVI_12], max_tif, "MAXIMUM", "DATA")
    arcpy.gp.CellStatistics_sa([NDVI_1,NDVI_2,NDVI_3,NDVI_4,NDVI_5,NDVI_6,NDVI_7,NDVI_8,NDVI_9,NDVI_10,NDVI_12], min_tif, "MINIMUM", "DATA")
    arcpy.gp.CellStatistics_sa([NDVI_1,NDVI_2,NDVI_3,NDVI_4,NDVI_5,NDVI_6,NDVI_7,NDVI_8,NDVI_9,NDVI_10,NDVI_12], mean_tif, "MEAN", "DATA")
    arcpy.gp.CellStatistics_sa([NDVI_1,NDVI_2,NDVI_3,NDVI_4,NDVI_5,NDVI_6,NDVI_7,NDVI_8,NDVI_9,NDVI_10,NDVI_12], range_tif, "RANGE", "DATA")
    arcpy.gp.CellStatistics_sa([NDVI_1,NDVI_2,NDVI_3,NDVI_4,NDVI_5,NDVI_6,NDVI_7,NDVI_8,NDVI_9,NDVI_10,NDVI_12], std_tif, "STD", "DATA")
    print n,NDVI_12
 
