# ---------------------------------------------------------------------------
# set null.py
# Created on: 2014-11-19 20:22:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")
for n in xrange(2009,2010):
	for m in xrange(1,2):
		m="%02d" % m	

		# Local variables:
		input = "I:\\AU\\01\\1\\NDVI-200001.tif"
		
		raster = "I:\\AU\\01\\1\\NDVI-1.tif"

		# Process: Raster Calculator
		arcpy.gp.RasterCalculator_sa("SetNull("input" ==  - 999,"input")", raster)

